- id: 50000000-0000-0000-0000-000000000006
  name: False state update
  description: Using the certificate of the node to continuing updating the status of the pods in Running.
  tactic: defense-evasion
  technique: { attack_id: T1027, name: "Obfuscated Files or Information" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "/opt/caldera/KC5/state-update.sh", timeout: 900, parsers: [], cleanup: "" } }