- id: 60000000-0000-0000-0000-000000000007
  name: Secrets collection
  description: Collection of the secrets from the etcd DB.
  tactic: credential-access
  technique: { attack_id: T1552.007, name: "Unsecured Credentials: Container API" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0607", timeout: 900, parsers: [], cleanup: "" } }