- id: 10000000-0000-0000-0000-000000000007
  name: Masquerading malicious deployment
  description: Simulation of a masqueration of a name deployment.
  tactic: defense-evasion
  technique: { attack_id: T1036.005, name: "Masquerading: Match Legitimate Resource Name or Location" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "echo \"[SIM] name masqueration of a deployment\"", timeout: 30 } }