# ========================
# Demo App configuration
# ========================
CLUSTER_TARGET=5Gcore
LAB_NAME=honeypotlab
FOLLOW_CONTROLLER_LOGS=true
SKIP_RESOURCE_CHECK=true
BUILD_CONTROLLER=true
PROXY_BIND_ALL=false
EXPOSE_TO_HOST=true
HOST_SOCKET=true
