# ========================
# ⚙️ Demo App configuration
# ========================
CLUSTER_TARGET=5Gcore
CLUSTER_PROFILE=honeypotlab
GENERIC_SVC_PORT=8085
FOLLOW_CONTROLLER_LOGS=true
SKIP_RESOURCE_CHECK=true
BUILD_CONTROLLER=true
PROXY_BIND_ALL=true
EXPOSE_TO_HOST=true
HOST_SOCKET=false
