apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: honeypot-app
build:
  local:
    push: true
    useBuildkit: true
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_VERSION}}"
  artifacts:
#    - image: accounting
#      context: .
#      docker:
#        dockerfile: src/accounting/Dockerfile
#    - image: ad
#      context: .
#      docker:
#        dockerfile: src/ad/Dockerfile
#    - image: attacker
#      context: src/attacker
#      docker:
#        dockerfile: src/attacker/Dockerfile
#        buildArgs:
#          GROUP: "cluster"
#          LOG_NS: "{{.MEM_NAMESPACE}}"
#          ATTACKED_NS: "{{.DMZ_NAMESPACE}}"
#          AUTH_NS: "{{.APP_NAMESPACE}}"
#          ATTACKERADDR: "{{.ATTACKER}}"
#          CALDERA_URL: "http://{{.CALDERA_SERVER}}:8888"
#          W101: "{{.W101}}"
#          W102: "{{.W102}}"
#          W103: "{{.W103}}"
#          W104: "{{.W104}}"
#          W105: "{{.W105}}"
#          W106: "{{.W106}}"
#          W107: "{{.W107}}"
#          W108: "{{.W108}}"
#    - image: auth
#      context: src/auth
#      docker:
#        dockerfile: src/auth/Dockerfile
#    - image: cart
#      context: .
#      docker:
#        dockerfile: src/cart/src/Dockerfile
#    - image: checkout
#      context: .
#      docker:
#        dockerfile: src/checkout/Dockerfile
#    - image: controller
#      context: src/controller
#      docker:
#        dockerfile: src/controller/Dockerfile
#    - image: currency
#      context: .
#      docker:
#        dockerfile: src/currency/Dockerfile
#        buildArgs:
#          EXPOSE_HTTP_PORT: "{{.CURRENCY_MIRROR_PORT}}"
#    - image: email
#      context: .
#      docker:
#        dockerfile: src/email/Dockerfile
#    - image: flagd
#      context: .
#      docker:
#        dockerfile: src/flagd/Dockerfile
#    - image: flagd-ui
#      context: .
#      docker:
#        dockerfile: src/flagd-ui/Dockerfile
#    - image: fraud-detection
#      context: .
#      docker:
#        dockerfile: src/fraud-detection/Dockerfile
#    - image: frontend
#      context: .
#      docker:
#        dockerfile: src/frontend/Dockerfile
#    - image: frontend-proxy
#      context: .
#      docker:
#        dockerfile: src/frontend-proxy/Dockerfile
#    - image: image-provider
#      context: .
#      docker:
#        dockerfile: src/image-provider/Dockerfile
#    - image: kafka
#      context: .
#      docker:
#        dockerfile: src/kafka/Dockerfile
#    - image: payment
#      context: .
#      docker:
#        dockerfile: src/payment/Dockerfile
#    - image: postgres
#      context: src/postgres
#      docker:
#        dockerfile: src/postgres/Dockerfile
#        buildArgs:
#          DB: "curr"
#    - image: postgres-auth
#      context: src/postgres
#      docker:
#        dockerfile: src/postgres/Dockerfile
#        buildArgs:
#          DB: "auth"
#    - image: postgres-payment
#      context: src/postgres
#      docker:
#        dockerfile: src/postgres/Dockerfile
#        buildArgs:
#          DB: "pay"
#    - image: product-catalog
#      context: .
#      docker:
#        dockerfile: src/product-catalog/Dockerfile
#    - image: quote
#      context: .
#      docker:
#        dockerfile: src/quote/Dockerfile
#    - image: recommendation
#      context: .
#      docker:
#        dockerfile: src/recommendation/Dockerfile
#    - image: shipping
#      context: .
#      docker:
#        dockerfile: src/shipping/Dockerfile
#    - image: sidecar-enc
#      context: src/sidecar-enc
#      docker:
#        dockerfile: src/sidecar-enc/Dockerfile
#    - image: sidecar-mal
#      context: src/sidecar-mal
#      docker:
#        dockerfile: src/sidecar-mal/Dockerfile
#    - image: smtp
#      context: src/smtp
#      docker:
#        dockerfile: src/smtp/Dockerfile
#    - image: valkey-cart
#      context: .
#      docker:
#        dockerfile: src/valkey-cart/Dockerfile
#    - image: traffic-translator
#      context: src/traffic-translator
#      docker:
#        dockerfile: src/traffic-translator/Dockerfile
deploy:
  statusCheck: true
  helm:
    flags:
      install:
        - --timeout=1h
      upgrade:
        - --timeout=1h
    releases:
      - name: metallb
        remoteChart: metallb
        repo: https://metallb.github.io/metallb
        namespace: metallb-system
        createNamespace: true
        wait: true
      - name: csi-driver-smb
        remoteChart: csi-driver-smb
        repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
        namespace: kube-system
        createNamespace: false
        wait: true
      - name: honeypot-additions
        chartPath: helm-charts/additions
        wait: true
        setValueTemplates:
        #Abilitations
          networkPolicies.enabled: "true"
          postgres.enabled: "true"
          config.enabled: "true"
          RBAC.enabled: "true"
          namespaces.enabled: "true"
          pool.enabled: "true"
          volumes.enabled: "true"
          registryAuth.enabled: "true"
        #Values
          default.image.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}"
          default.image.version: "{{.IMAGE_VERSION}}"
          networkPolicies.rules.dmz.name: "{{.DMZ_NAMESPACE}}"
          networkPolicies.rules.dmz.ingress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.TST_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.dmz.egress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.TST_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.pay.name: "{{.PAY_NAMESPACE}}"
          networkPolicies.rules.pay.ingress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DAT_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.pay.egress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DAT_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.app.name: "{{.APP_NAMESPACE}}"
          networkPolicies.rules.app.ingress: "{{.DAT_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.app.egress: "{{.DAT_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.dat.name: "{{.DAT_NAMESPACE}}"
          networkPolicies.rules.dat.ingress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.dat.egress: "{{.APP_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.mem.name: "{{.MEM_NAMESPACE}}"
          networkPolicies.rules.mem.ingress: "{{.DAT_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, {{.TST_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.mem.egress: "{{.DAT_NAMESPACE}}\\, {{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, {{.PAY_NAMESPACE}}\\, {{.TST_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.tst.name: "{{.TST_NAMESPACE}}"
          networkPolicies.rules.tst.ingress: "{{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, kube-system"
          networkPolicies.rules.tst.egress: "{{.MEM_NAMESPACE}}\\, {{.DMZ_NAMESPACE}}\\, kube-system"
          postgres.namespace: "{{.DAT_NAMESPACE}}"
          config.objects.flagd-credentials-ui.namespace: "{{.MEM_NAMESPACE}}"
          config.objects.proto.namespace: "{{.APP_NAMESPACE}}"
          config.objects.product-catalog-products.namespace: "{{.APP_NAMESPACE}}"
          config.objects.flagd-config.namespace: "{{.MEM_NAMESPACE}}"
          config.objects.dbcurrency-creds.namespace: "{{.APP_NAMESPACE}}"
          config.objects.dbcurrency.namespace: "{{.DAT_NAMESPACE}}"
          config.objects.dbpayment.namespace: "{{.DAT_NAMESPACE}}"
          config.objects.dbauth.namespace: "{{.DAT_NAMESPACE}}"
          config.objects.smb-creds.namespace: "{{.MEM_NAMESPACE}}"
          namespaces.list: '{{.APP_NAMESPACE}}\, {{.DMZ_NAMESPACE}}\, {{.DAT_NAMESPACE}}\, {{.PAY_NAMESPACE}}\, {{.MEM_NAMESPACE}}\, {{.TST_NAMESPACE}}'
          registryAuth.username: "{{.REGISTRY_USER}}"
          registryAuth.password: "{{.REGISTRY_PASS}}"
          pool.ips: "{{.FRONTEND_PROXY_IP}}-{{.FRONTEND_PROXY_IP}}"
        #Vulnerabilities
          vulnerabilities.dnsGrant: "{{ if eq .DNS_GRANT \"true\" }}true{{ else }}false{{ end }}"
          vulnerabilities.deployGrant: "{{ if eq .DEPLOY_GRANT \"true\" }}true{{ else }}false{{ end }}"
          vulnerabilities.anonymousGrant: "{{ ternary `false` `true` (or (ne .ANONYMOUS_AUTH `true`) (ne .ANONYMOUS_GRANT `true`)) }}"
          vulnerabilities.currencyGrant: "{{ if eq .CURRENCY_GRANT \"true\" }}true{{ else }}false{{ end }}"
          config.objects.flagd-credentials-ui.type: "{{ if eq .FLAGD_CONFIGMAP \"true\" }}configmap{{ else }}secret{{ end }}"
        valuesFiles:
          - helm-charts/additions/values.yaml
      - name: honeypot-telemetry
        chartPath: helm-charts/telemetry
        namespace: "{{.MEM_NAMESPACE}}"
        wait: true
        setValueTemplates:
        #Abilitations
          opentelemetry-collector.enabled: "true"
          jaeger.enabled: "true"
          prometheus.enabled: "true"
          grafana.enabled: "true"
          opensearch.enabled: "true"
        #Values
          opentelemetry-collector.config.receivers.httpcheck/frontend-proxy.targets[0].endpoint: "http://frontend-proxy.{{.DMZ_NAMESPACE}}:8080"
          opentelemetry-collector.config.receivers.redis.endpoint: "valkey-cart.{{.DAT_NAMESPACE}}:6379"
        valuesFiles:
          - helm-charts/telemetry/values-{{ (ternary "noauth" "auth" (eq (env "LOG_OPEN") "true")) }}.yaml
      - name: honeypot-astronomy-shop
        chartPath: helm-charts/astronomy-shop
        setValueTemplates:
        #Abilitations
          components.test-image.enabled: "true"
          components.frontend-proxy.enabled: "true"
          components.image-provider.enabled: "true"
          components.valkey-cart.enabled: "true"
          components.payment.enabled: "true"
          components.flagd.enabled: "true"
          components.traffic-controller.enabled: "true"
          components.accounting.enabled: "true"
          components.ad.enabled: "true"
          components.auth.enabled: "true"
          components.cart.enabled: "true"
          components.checkout.enabled: "true"
          components.currency.enabled: "true"
          components.email.enabled: "true"
          components.fraud-detection.enabled: "true"
          components.frontend.enabled: "true"
          components.product-catalog.enabled: "true"
          components.quote.enabled: "true"
          components.recommendation.enabled: "true"
          components.shipping.enabled: "true"
          components.smtp.enabled: "true"
          components.kafka.enabled: "true"
        #Values
          default.env[1].value: "otel-collector.{{.MEM_NAMESPACE}}"
          default.image.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}"
          components.accounting.namespace: "{{.APP_NAMESPACE}}"
          components.ad.namespace: "{{.APP_NAMESPACE}}"
          components.ad.env[1].value: "flagd.{{.MEM_NAMESPACE}}"
          components.auth.namespace: "{{.APP_NAMESPACE}}"
          components.auth.env[0].value: "postgres-auth.{{.DAT_NAMESPACE}}"
          components.auth.initContainers[0].env[0].value: "postgres-auth.{{.DAT_NAMESPACE}}"
          components.cart.namespace: "{{.APP_NAMESPACE}}"
          components.cart.env[2].value: "valkey-cart.{{.DAT_NAMESPACE}}:6379"
          components.cart.env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.cart.initContainers[0].env[0].value: "valkey-cart.{{.DAT_NAMESPACE}}"
          components.checkout.namespace: "{{.APP_NAMESPACE}}"
          components.checkout.env[8].value: "flagd.{{.MEM_NAMESPACE}}"
          components.checkout.initContainers[1].env[0].value: "flagd.{{.MEM_NAMESPACE}}"
          components.checkout.sidecarContainers[0].imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/sidecar-enc"
          components.checkout.sidecarContainers[0].env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.checkout.sidecarContainers[1].imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/sidecar-enc"
          components.checkout.sidecarContainers[1].env[2].value: "payment.{{.PAY_NAMESPACE}}:8080"
          components.checkout.sidecarContainers[1].env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.currency.namespace: "{{.APP_NAMESPACE}}"
          components.currency.env[4].value: "postgres.{{.DAT_NAMESPACE}}"
          components.currency.initContainers[0].env[0].value: "postgres.{{.DAT_NAMESPACE}}"
          components.email.namespace: "{{.APP_NAMESPACE}}"
          components.fraud-detection.namespace: "{{.APP_NAMESPACE}}"
          components.fraud-detection.env[1].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend.namespace: "{{.APP_NAMESPACE}}"
          components.frontend.env[10].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend.initContainers[0].env[0].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend.sidecarContainers[0].imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/sidecar-enc"
          components.frontend.sidecarContainers[0].env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend-proxy.namespace: "{{.DMZ_NAMESPACE}}"
          components.frontend-proxy.service.loadBalancerIP: "{{.FRONTEND_PROXY_IP}}"
          components.frontend-proxy.env[1].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend-proxy.env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.frontend-proxy.env[5].value: "frontend.{{.APP_NAMESPACE}}"
          components.frontend-proxy.env[7].value: "grafana.{{.MEM_NAMESPACE}}"
          components.frontend-proxy.env[11].value: "jaeger-query.{{.MEM_NAMESPACE}}"
          components.image-provider.namespace: "{{.DMZ_NAMESPACE}}"
          components.image-updater.namespace: "{{.MEM_NAMESPACE}}"
          components.image-updater.imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/controller"
          components.image-updater.env[2].value: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}"
          components.image-updater.env[3].value: "{{.REGISTRY_USER}}"
          components.image-updater.env[4].value: "{{.REGISTRY_PASS}}"
          components.payment.namespace: "{{.PAY_NAMESPACE}}"
          components.payment.env[1].value: "flagd.{{.MEM_NAMESPACE}}"
          components.payment.env[4].value: "postgres-payment.{{.DAT_NAMESPACE}}"
          components.payment.initContainers[0].env[0].value: "flagd.{{.MEM_NAMESPACE}}"
          components.payment.initContainers[1].env[0].value: "postgres-payment.{{.DAT_NAMESPACE}}"
          components.payment.sidecarContainers[0].imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/sidecar-enc"
          components.payment.sidecarContainers[0].env[3].value: "flagd.{{.MEM_NAMESPACE}}"
          components.product-catalog.namespace: "{{.APP_NAMESPACE}}"
          components.product-catalog.env[2].value: "flagd.{{.MEM_NAMESPACE}}"
          components.quote.namespace: "{{.APP_NAMESPACE}}"
          components.recommendation.namespace: "{{.APP_NAMESPACE}}"
          components.recommendation.env[4].value: "flagd.{{.MEM_NAMESPACE}}"
          components.shipping.namespace: "{{.APP_NAMESPACE}}"
          components.smtp.namespace: "{{.DMZ_NAMESPACE}}"
          components.flagd.namespace: "{{.MEM_NAMESPACE}}"
          components.kafka.namespace: "{{.APP_NAMESPACE}}"
          components.test-image.namespace: "{{.TST_NAMESPACE}}"
          components.test-image.imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/attacker"
          components.test-image.env[0].value: "http://{{.CALDERA_SERVER}}:8888"
          components.traffic-controller.namespace: "{{.MEM_NAMESPACE}}"
          components.traffic-controller.imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/controller"
          components.traffic-controller.sidecarContainers[0].imageOverride.repository: "{{.REGISTRY_NAME}}:{{.REGISTRY_PORT}}/traffic-translator"
          components.valkey-cart.namespace: "{{.DAT_NAMESPACE}}"
        #Vulnerabilities
          components.traffic-controller.env[4].value: "{{ if eq .LOG_TOKEN \"true\" }}synthetic-log.sh{{ else }}null.sh{{ end }}"
          components.image-updater.enabled: "{{ if eq .AUTO_DEPLOY \"true\" }}true{{ else }}false{{ end }}"
          components.smtp.hostNetwork: "{{ if eq .HOST_NETWORK \"true\" }}true{{ else }}false{{ end }}"
          components.smtp.env[0].value: "{{ if eq .RCE_VULN \"true\" }}true{{ else }}false{{ end }}"
          components.smtp.additionalVolumes[0].hostPath.path: '{{ if eq (env "SOCKET_SHARED") "true" }}/run/containerd/containerd.sock{{ else }}/tmp/disabled-containerd.sock{{ end }}'
          components.smtp.additionalVolumes[0].hostPath.type: '{{ if eq (env "SOCKET_SHARED") "true" }}Socket{{ else }}FileOrCreate{{ end }}'
          components.currency.env[9].value: "{{ if eq .FLAGD_FEATURES \"true\" }}true{{ else }}false{{ end }}"
          components.checkout.sidecarContainers[0].env[7].value: "{{ if eq .FLAGD_FEATURES \"true\" }}true{{ else }}false{{ end }}"
          components.checkout.sidecarContainers[1].env[7].value: "{{ if eq .FLAGD_FEATURES \"true\" }}true{{ else }}false{{ end }}"
          components.frontend.sidecarContainers[0].env[7].value: "{{ if eq .FLAGD_FEATURES \"true\" }}true{{ else }}false{{ end }}"
          components.payment.sidecarContainers[0].env[7].value: "{{ if eq .FLAGD_FEATURES \"true\" }}true{{ else }}false{{ end }}"
          components.flagd.sidecarContainers[0].envSwitchFrom[0].valueFrom: "{{ if eq .FLAGD_CONFIGMAP \"true\" }}configmap{{ else }}secret{{ end }}"
          components.flagd.sidecarContainers[0].envSwitchFrom[1].valueFrom: "{{ if eq .FLAGD_CONFIGMAP \"true\" }}configmap{{ else }}secret{{ end }}"
        valuesFiles:
          - helm-charts/astronomy-shop/values.yaml
