- id: 30000000-0000-0000-0000-000000000006
  name: Path traversal currency service
  description: Path traversal to currency service with the aim of stealing its ticket.
  tactic: credential-access
  technique: { attack_id: T1212, name: "Exploitation for Credential Access" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0306", timeout: 30 } }