- id: 30000000-0000-0000-0000-000000000007
  name: Job creation for injecting DB entry
  description: Job creation with the secrets of currency service (currency DB) to inject an entry.
  tactic: execution
  technique: { attack_id: T1059, name: "Command and Scripting Interpreter" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "/opt/caldera/KC3/job-creation.sh", timeout: 900, parsers: [], cleanup: "" } }