apiVersion: v2
type: application
name: opentelemetry-demo
version: 0.37.2
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-demo
maintainers:
  - name: dmitryax
  - name: jaronoff97
  - name: puckpuck
  - name: tylerhelmuth
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 2.0.2
