{{- if .Values.caldera.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
  namespace: {{ .Values.caldera.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels: { app: caldera }
  template:
    metadata:
      labels: { app: caldera }
    spec:
      containers:
        - name: caldera-proxy
          image: alpine/socat:1.8.0.0
          imagePullPolicy: "{{ .Values.default.image.pullPolicy }}"
          args: ["-d","-d","TCP-LISTEN:{{ .Values.caldera.port }},fork,reuseaddr","TCP:{{ .Values.caldera.host }}:{{ .Values.caldera.port }}"]
          ports:
          - containerPort: {{ .Values.caldera.port }}
          readinessProbe:
            tcpSocket: { port: {{ .Values.caldera.port }} }
            initialDelaySeconds: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: caldera-proxy
  namespace: {{ .Values.caldera.namespace }}
spec:
  selector: { app: caldera }
  ports:
    - name: http
      port: {{ .Values.caldera.port }}
      targetPort: {{ .Values.caldera.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}