{{- if .Values.namespaces.enabled }}
{{- $list := splitList "," .Values.namespaces.list }}
{{- range $ns := $list }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ trim $ns | quote }}
---
{{- end }}
{{- end }}

{{- if and .Values.namespaces.enabled .Values.registryAuth.enabled }}
{{- $list := splitList "," .Values.namespaces.list }}
{{- $server := required "registryAuth.server is required" .Values.registryAuth.server }}
{{- $user := required "registryAuth.username is required" .Values.registryAuth.username }}
{{- $pass := required "registryAuth.password is required" .Values.registryAuth.password }}
{{- $email := default "noreply@example.com" .Values.registryAuth.email }}
{{- $secretName := default "regcred" .Values.registryAuth.secretName }}
{{- $saName := default "puller" .Values.registryAuth.serviceAccountName }}

{{- $auth := printf "%s:%s" $user $pass | b64enc }}
{{- $dockercfg := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $server $user $pass $email $auth }}

{{- range $ns := $list }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ trim $ns | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockercfg | b64enc }}
{{- end }}
{{- end }}