{{- if .Values.networkPolicies.enabled -}}
{{- $root := . -}}

{{- range $key, $cfg := .Values.networkPolicies.rules -}}
{{- $ns := (default $key $cfg.name) | trim -}}
{{- $allowWorldEgress := (default false $cfg.allowInternetEgress) -}}
{{- $allowWorldIngress := (default false $cfg.allowInternetIngress) -}}

{{- /* Build lists of namespace peers */ -}}
{{- $ingList := splitList "," (default "" $cfg.ingress) -}}
{{- $ingPeers := list -}}
{{- range $ingList }}
  {{- $p := trim . -}}
  {{- if $p }}{{- $ingPeers = append $ingPeers $p }}{{- end -}}
{{- end -}}
{{- $egList := splitList "," (default "" $cfg.egress) -}}
{{- $egPeers := list -}}
{{- range $egList }}
  {{- $p := trim . -}}
  {{- if $p }}{{- $egPeers = append $egPeers $p }}{{- end -}}
{{- end -}}

{{- $internetCfg := (default dict $root.Values.networkPolicies.internet) -}}
{{- $internetIngressCidrs := (default (list) $internetCfg.ingressCidrs) -}}
{{- $internetEgressCidrs := (default (list) $internetCfg.egressCidrs) -}}
{{- $internetExceptCidrs := (default (list) $internetCfg.exceptCidrs) -}}
{{- $hasIngressCidrs := gt (len $internetIngressCidrs) 0 -}}
{{- $hasEgressCidrs  := gt (len $internetEgressCidrs) 0 -}}
{{- $kubeApiCfg := (default dict $root.Values.networkPolicies.kubeAPIServer) -}}
{{- $kubeIngressRaw := (default (list) $kubeApiCfg.ingressIPs) -}}
{{- if and (eq (len $kubeIngressRaw) 0) (gt (len (default (list) $kubeApiCfg.ingressCidrs)) 0) -}}
  {{- $kubeIngressRaw = (default (list) $kubeApiCfg.ingressCidrs) -}}
{{- end -}}
{{- if kindIs "string" $kubeIngressRaw -}}
  {{- $kubeIngressRaw = splitList "," $kubeIngressRaw -}}
{{- end -}}
{{- $kubeIngressCidrs := list -}}
{{- range $entry := $kubeIngressRaw -}}
  {{- $raw := trim (toString $entry) -}}
  {{- if $raw -}}
    {{- if contains "/" $raw -}}
      {{- if or (hasSuffix "/32" $raw) (hasSuffix "/128" $raw) -}}
        {{- $kubeIngressCidrs = append $kubeIngressCidrs $raw -}}
      {{- else -}}
        {{- fail (printf "networkPolicies.kubeAPIServer.ingressIPs accepts only single-host entries (/32 or /128), got %q" $raw) -}}
      {{- end -}}
    {{- else -}}
      {{- if contains ":" $raw -}}
        {{- $kubeIngressCidrs = append $kubeIngressCidrs (printf "%s/128" $raw) -}}
      {{- else -}}
        {{- $kubeIngressCidrs = append $kubeIngressCidrs (printf "%s/32" $raw) -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- $kubeEgressRaw := (default (list) $kubeApiCfg.egressIPs) -}}
{{- if and (eq (len $kubeEgressRaw) 0) (gt (len (default (list) $kubeApiCfg.egressCidrs)) 0) -}}
  {{- $kubeEgressRaw = (default (list) $kubeApiCfg.egressCidrs) -}}
{{- end -}}
{{- if kindIs "string" $kubeEgressRaw -}}
  {{- $kubeEgressRaw = splitList "," $kubeEgressRaw -}}
{{- end -}}
{{- $kubeEgressCidrs := list -}}
{{- range $entry := $kubeEgressRaw -}}
  {{- $raw := trim (toString $entry) -}}
  {{- if $raw -}}
    {{- if contains "/" $raw -}}
      {{- if or (hasSuffix "/32" $raw) (hasSuffix "/128" $raw) -}}
        {{- $kubeEgressCidrs = append $kubeEgressCidrs $raw -}}
      {{- else -}}
        {{- fail (printf "networkPolicies.kubeAPIServer.egressIPs accepts only single-host entries (/32 or /128), got %q" $raw) -}}
      {{- end -}}
    {{- else -}}
      {{- if contains ":" $raw -}}
        {{- $kubeEgressCidrs = append $kubeEgressCidrs (printf "%s/128" $raw) -}}
      {{- else -}}
        {{- $kubeEgressCidrs = append $kubeEgressCidrs (printf "%s/32" $raw) -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- $hasKubeIngressCidrs := and $root.Values.networkPolicies.allowKubeAPIServer (gt (len $kubeIngressCidrs) 0) -}}
{{- $hasKubeEgressCidrs  := and $root.Values.networkPolicies.allowKubeAPIServer (gt (len $kubeEgressCidrs) 0) -}}

{{- $emitIngressBase := or (gt (len $ingPeers) 0) $hasIngressCidrs $root.Values.networkPolicies.allowSameNamespace $allowWorldIngress -}}
{{- $emitEgressBase  := or (gt (len $egPeers) 0) $hasEgressCidrs  $root.Values.networkPolicies.allowSameNamespace $allowWorldEgress  -}}
{{- $emitIngress := or $emitIngressBase $hasKubeIngressCidrs -}}
{{- $emitEgress  := or $emitEgressBase  $hasKubeEgressCidrs  -}}
{{- $policySelector := (default $root.Values.networkPolicies.podSelector $cfg.podSelector) -}}

{{- if or $emitIngress $emitEgress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-allow" $ns | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
spec:
  {{- if $policySelector }}
  podSelector:
{{ toYaml $policySelector | indent 4 }}
  {{- else }}
  podSelector: {}
  {{- end }}

  {{- if $emitIngress }}
  ingress:
    {{- if $emitIngressBase }}
    - from:
        {{- /* namespace peers for ingress */}}
        {{- range $ingPeers }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
          podSelector: {}
        {{- end }}
        {{- if $root.Values.networkPolicies.allowSameNamespace }}
        - podSelector: {}
        {{- end }}

        {{- if $allowWorldIngress }}
          {{- $mode := (default "world" $root.Values.networkPolicies.internet.mode) -}}
          {{- if eq $mode "world" }}
        - ipBlock:
            cidr: "0.0.0.0/0"
        - ipBlock:
            cidr: "::/0"
          {{- else if eq $mode "cidr" }}
              {{- range $internetIngressCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
              {{- end }}
              {{- if and (gt (len $internetIngressCidrs) 0) (gt (len $internetExceptCidrs) 0) }}
        - ipBlock:
            cidr: "0.0.0.0/0"
            except:
              {{- range $ex := $internetExceptCidrs }}
              - {{ $ex | quote }}
              {{- end }}
              {{- end }}
          {{- else }}
        # Unknown internet.mode -> no Internet ingress opened
          {{- end }}
        {{- end }}

        {{- /* global legacy Internet (if defined but not enabled per-namespace) */}}
          {{- if and (gt (len $internetIngressCidrs) 0) (not $allowWorldIngress) }}
              {{- range $internetIngressCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
              {{- end }}
          {{- end }}
          {{- if and (gt (len $internetIngressCidrs) 0) (gt (len $internetExceptCidrs) 0) (not $allowWorldIngress) }}
        - ipBlock:
            cidr: "0.0.0.0/0"
            except:
              {{- range $ex := $internetExceptCidrs }}
              - {{ $ex | quote }}
              {{- end }}
          {{- end }}
    {{- end }}
    {{- if $hasKubeIngressCidrs }}
    - from:
        {{- range $cidr := $kubeIngressCidrs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
        {{- end }}
    {{- end }}
  {{- end }}

  {{- if $emitEgress }}
  egress:
    {{- if $emitEgressBase }}
    - to:
        {{- /* namespace peers for egress */}}
        {{- range $egPeers }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
          podSelector: {}
        {{- end }}
        {{- if $root.Values.networkPolicies.allowSameNamespace }}
        - podSelector: {}
        {{- end }}

        {{- if $allowWorldEgress }}
          {{- $mode := (default "world" $root.Values.networkPolicies.internet.mode) -}}
          {{- if eq $mode "world" }}
        - ipBlock:
            cidr: "0.0.0.0/0"
        - ipBlock:
            cidr: "::/0"
          {{- else if eq $mode "cidr" }}
              {{- if gt (len $internetEgressCidrs) 0 }}
              {{- range $internetEgressCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
              {{- end }}
              {{- if and (gt (len $internetEgressCidrs) 0) (gt (len $internetExceptCidrs) 0) }}
        - ipBlock:
            cidr: "0.0.0.0/0"
            except:
              {{- range $ex := $internetExceptCidrs }}
              - {{ $ex | quote }}
              {{- end }}
              {{- end }}
              {{- else }}
        - ipBlock:
            cidr: "0.0.0.0/0"
        - ipBlock:
            cidr: "::/0"
              {{- end }}
          {{- else }}
        # Unknown internet.mode -> no Internet egress opened
          {{- end }}
        {{- end }}

          {{- if and (gt (len $internetEgressCidrs) 0) (not $allowWorldEgress) }}
              {{- range $internetEgressCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
              {{- end }}
          {{- end }}
          {{- if and (gt (len $internetEgressCidrs) 0) (gt (len $internetExceptCidrs) 0) (not $allowWorldEgress) }}
        - ipBlock:
            cidr: "0.0.0.0/0"
            except:
              {{- range $ex := $internetExceptCidrs }}
              - {{ $ex | quote }}
              {{- end }}
          {{- end }}
    {{- end }}
    {{- if $hasKubeEgressCidrs }}
    - to:
        {{- range $cidr := $kubeEgressCidrs }}
        - ipBlock:
            cidr: {{ $cidr | quote }}
        {{- end }}
    {{- end }}
  {{- end }}

  policyTypes:
  {{- if $emitIngress }}
    - Ingress
  {{- end }}
  {{- if $emitEgress }}
    - Egress
  {{- end }}
{{- end }}

{{- if $root.Values.networkPolicies.defaultDeny }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-default-deny" $ns | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
spec:
  {{- if $policySelector }}
  podSelector:
{{ toYaml $policySelector | indent 4 }}
  {{- else }}
  podSelector: {}
  {{- end }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}

{{- end }}{{/* range rules */}}
{{- end }}{{/* if enabled */}}
