{{- if .Values.caldera.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
spec:
  replicas: 1
  selector:
    matchLabels: { app: caldera }
  template:
    metadata:
      labels: { app: caldera }
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: "{{ .Values.caldera.controller.name }}"
          image: "{{ .Values.default.image.repository }}/{{ .Values.caldera.controller.name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.default.image.pullPolicy }}"
          env:
            - name: GROUP
              value: "{{ .Values.caldera.controller.env.group }}"
            - name: ADV_LIST
              value: "{{ .Values.caldera.controller.env.advList }}"
            - name: CALDERA_URL
              value: "{{ .Values.caldera.controller.env.calderaUrl }}"
            - name: PLANNER
              value: "{{ .Values.caldera.controller.env.planner }}"
            - name: OP_NAME_PREFIX
              value: "{{ .Values.caldera.controller.env.opNamePrefix }}"
            - name: CALDERA_KEY
              value: "{{ .Values.caldera.controller.env.calderaKey }}"
        - name: caldera-proxy
          image: alpine/socat:1.8.0.0
          imagePullPolicy: "{{ .Values.default.image.pullPolicy }}"
          args: ["-d","-d","TCP-LISTEN:{{ .Values.caldera.port }},fork,reuseaddr","TCP:{{ .Values.caldera.ip }}:{{ .Values.caldera.port }}"]
          ports:
          - containerPort: {{ .Values.caldera.port }}
          readinessProbe:
            tcpSocket: { port: {{ .Values.caldera.port }} }
            initialDelaySeconds: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: caldera
spec:
  selector: { app: caldera }
  ports:
    - name: http
      port: {{ .Values.caldera.port }}
      targetPort: {{ .Values.caldera.port }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: caldera-proxy
spec:
  ports:
    - name: "tcp-{{ .Values.caldera.port }}"
      port: {{ .Values.caldera.port }}
      targetPort: {{ .Values.caldera.port }}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: caldera-proxy
subsets:
  - addresses:
      - ip: {{ .Values.caldera.ip }}
    ports:
      - port: {{ .Values.caldera.port }}
        protocol: TCP
{{- end }}