{{- if (index .Values.components "product-catalog").enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-products
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "products/*.json").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proto
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
data:
  demo.proto: |-
    {{ .Files.Get "proto/demo.proto" | nindent 4 }}
{{- end }}
