apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: ghcr.io/open-telemetry/demo-email:2.0.2
        ports:
        - containerPort: 6060
        livenessProbe:
          httpGet:
            path: /
            port: 6060
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 6060
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: demo-config
