apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  namespace: demo
spec:
  selector:
    app: frontend-proxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
