apiVersion: v1
kind: Service
metadata:
  name: image-provider
  namespace: demo
spec:
  selector:
    app: image-provider
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
