apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: demo
spec:
  selector:
    app: load-generator
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  type: ClusterIP
