apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: demo
spec:
  selector:
    app: otel-collector
  ports:
  - protocol: TCP
    port: 4317
    targetPort: 4317
  type: ClusterIP
