apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: demo
spec:
  selector:
    app: product-catalog
  ports:
  - protocol: TCP
    port: 3550
    targetPort: 3550
  type: ClusterIP
