apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote
        image: ghcr.io/open-telemetry/demo-quote:2.0.2
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: demo-config
