apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: demo
spec:
  selector:
    app: recommendation
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
  type: ClusterIP
